add opentelemetry version 1.19.0
oracle/graalvm-reachability-metadata pull request #215
Opened 2023-02-01 15:52 UTC by n0tl3ss

## What does this PR do?

Adds reflect config and tests for 

- `io.opentelemetry:opentelemetry-exporter-jaeger:1.19.0`
- `io.opentelemetry:opentelemetry-exporter-logging:1.19.0`
- `io.opentelemetry:opentelemetry-exporter-otlp:1.19.0`
- `io.opentelemetry:opentelemetry-exporter-zipkin:1.19.0`
- `io.opentelemetry:opentelemetry-sdk-metrics:1.19.0`
- `io.opentelemetry:opentelemetry-sdk-trace:1.19.0`

2023-02-02 09:54 UTC, dnestoro requested changes
Hey Nemanja, thanks for your contribution. It seems like you didn't add new entries in `metadata/index.json` file. I am working on a fix to fail ci jobs in this case, so we don't need to wait for a review to catch these kind of bugs.

Can you please wait for my PR to be merged so I can test how it works on the real problem? I will notify you when the PR is merged

2023-02-06 12:35 UTC, dnestoro commented
Hey @n0tl3ss,  you can add missing entries in `metadata/index.json` now, since I fixed CI to fail when changed metadata is not present in the index file.

2023-02-06 15:44 UTC, n0tl3ss commented
Hi @dnestoro I think its ready for review. I also added `-H:+AddAllCharsets` argument to GraalVM compiler. Without it Zipkin test throws `java.nio.charset.UnsupportedCharsetException: UTF-32BE`.

2023-02-07 16:18 UTC, dnestoro requested changes

2023-02-08 12:52 UTC, merged