Add testcontainers/ryuk docker image to the allowed images list
oracle/graalvm-reachability-metadata pull request #262
Opened 2023-04-03 18:04 UTC by linghengqian

## What does this PR do?

- For https://github.com/oracle/graalvm-reachability-metadata/pull/170 and https://github.com/oracle/graalvm-reachability-metadata/issues/164.
- Related to https://github.com/oracle/graalvm-reachability-metadata/issues/250.
- Add testcontainers/ryuk docker image to the allowed images list.
```shell
grype testcontainers/ryuk:0.3.4
 ✔ Vulnerability DB        [no update available]
 ✔ Pulled image            
 ✔ Loaded image            
 ✔ Parsed image            
 ✔ Cataloged packages      [29 packages]
 ✔ Scanning image...       [97 vulnerabilities]
   ├── 3 critical, 71 high, 21 medium, 2 low, 0 negligible
   └── 67 fixed
NAME                            INSTALLED                                               FIXED-IN                           TYPE       VULNERABILITY        SEVERITY 
busybox                         1.32.1-r6                                               1.32.1-r7                          apk        CVE-2021-42374       Medium    
busybox                         1.32.1-r6                                               1.32.1-r7                          apk        CVE-2021-42375       Medium    
busybox                         1.32.1-r6                                               1.32.1-r7                          apk        CVE-2021-42378       High      
busybox                         1.32.1-r6                                               1.32.1-r7                          apk        CVE-2021-42379       High      
busybox                         1.32.1-r6                                               1.32.1-r7                          apk        CVE-2021-42380       High      
busybox                         1.32.1-r6                                               1.32.1-r7                          apk        CVE-2021-42381       High      
busybox                         1.32.1-r6                                               1.32.1-r7                          apk        CVE-2021-42382       High      
busybox                         1.32.1-r6                                               1.32.1-r7                          apk        CVE-2021-42383       High      
busybox                         1.32.1-r6                                               1.32.1-r7                          apk        CVE-2021-42384       High      
busybox                         1.32.1-r6                                               1.32.1-r7                          apk        CVE-2021-42385       High      
busybox                         1.32.1-r6                                               1.32.1-r7                          apk        CVE-2021-42386       High      
busybox                         1.32.1-r6                                               1.32.1-r8                          apk        CVE-2022-28391       High      
busybox                         1.32.1-r6                                               1.32.1-r9                          apk        CVE-2022-30065       High      
github.com/docker/distribution  v2.6.0-rc.1.0.20180105232752-277ed486c948+incompatible  2.7.0-rc.0                         go-module  GHSA-h62f-wm92-2cmw  High      
github.com/docker/distribution  v2.6.0-rc.1.0.20180105232752-277ed486c948+incompatible  2.8.0                              go-module  GHSA-qq97-vm5h-rrhg  Low       
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2014-0048        Critical  
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2014-8178        Medium    
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2014-8179        High      
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2015-3627        High      
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2015-3630        High      
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2015-3631        Low       
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2016-3697        High      
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2017-14992       Medium    
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2019-13139       High      
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2019-13509       High      
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2019-15752       High      
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2019-16884       High      
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2019-5736        High      
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2020-27534       Medium    
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2021-21284       Medium    
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2021-21285       Medium    
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2021-3162        High      
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                                                       go-module  CVE-2022-25365       High      
github.com/docker/docker        v1.4.2-0.20170502054910-90d35abf7b35                    1.6.1                              go-module  GHSA-g7v2-2qxx-wjrw  Medium    
golang.org/x/crypto             v0.0.0-20180112200814-13931e22f9e7                      0.0.0-20190320223903-b7391e95e576  go-module  GHSA-r5c5-pr8j-pfp7  Medium    
golang.org/x/crypto             v0.0.0-20180112200814-13931e22f9e7                      0.0.0-20200124225646-8b5121be2f68  go-module  GHSA-cjjc-xp8v-855w  High      
golang.org/x/crypto             v0.0.0-20180112200814-13931e22f9e7                      0.0.0-20200220183623-bac4c82f6975  go-module  GHSA-ffhg-7mh4-33c4  High      
golang.org/x/crypto             v0.0.0-20180112200814-13931e22f9e7                      0.0.0-20201216223049-8b5274cf687f  go-module  GHSA-3vm4-22fp-5rfm  High      
golang.org/x/crypto             v0.0.0-20180112200814-13931e22f9e7                      0.0.0-20211202192323-5770296d904e  go-module  GHSA-gwc9-m7rh-j2ww  High      
golang.org/x/crypto             v0.0.0-20180112200814-13931e22f9e7                      0.0.0-20220314234659-1baeb1ce4c0b  go-module  GHSA-8c26-wmh5-6g9v  High      
golang.org/x/net                v0.0.0-20180906233101-161cd47e91fd                      0.0.0-20180921000356-2f5d2388922f  go-module  GHSA-fcf9-6fv2-fc5v  High      
golang.org/x/net                v0.0.0-20180906233101-161cd47e91fd                      0.0.0-20180925071336-cf3bd585ca2a  go-module  GHSA-2wp2-chmh-r934  High      
golang.org/x/net                v0.0.0-20180906233101-161cd47e91fd                      0.0.0-20190125002852-4b62a64f59f7  go-module  GHSA-4r78-hx75-jjj2  High      
golang.org/x/net                v0.0.0-201 [...]

2023-09-09 14:48 UTC, linghengqian reviewed
- Call @matneu to help with the review.

2023-09-25 12:14 UTC, matneu requested changes
Based on the testcontainers information [here](https://java.testcontainers.org/features/configuration/#disabling-ryuk), ryuk has to run privileged, which is a no-go for us.

2023-09-25 13:12 UTC, linghengqian commented
- @matneu Does the project allow global setting of `.env` file, in which `TESTCONTAINERS_RYUK_DISABLED=true` is configured by default?  This will avoid the tedious setup of each test folder.

2023-10-20 08:44 UTC, dnestoro commented
@linghengqian we cannot allow global `.env` for docker images. Please close the PR unless you have some other idea how to solve this

2023-10-20 13:46 UTC, linghengqian commented
> @linghengqian we cannot allow global `.env` for docker images. Please close the PR unless you have some other idea how to solve this

- @dnestoro I have another question, are `.env` files allowed to exist in submodules where unit tests are located?  The Contributor Guidelines don't make this clear.

2023-10-23 13:29 UTC, linghengqian commented
> @linghengqian local `env` file is okay. We cannot allow global `env` files, but as long as you are affecting only your test, it is okay. Anyway, even with the `env` variable, do you still need this docker image for your test? If so, then @matneu can we accept this docker image if it is not run as privileged container? 

- Thanks for the clarification.  I will use a local `.env` file to introduce the use of testcontainer in the relevant unit tests of jetcd-core.  This PR will be closed.

2023-10-23 13:29 UTC, closed without merging