add log4j 1.2.17 metadata
oracle/graalvm-reachability-metadata pull request #369
Opened 2023-08-16 12:03 UTC by FoghostCn

## What does this PR do?

add metadata for log4j 1.2.17

## Checklist before merging
- [ ] I have considered including reachability metadata directly in the library or the framework (see [our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md))
- [ ] I am the original author of all content provided in the pull request, and I did not copy the content from any other source (see [the tests section from our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#tests))
- [ ] For all tests where I am not the sole author, I have added a comment that proves I may publish them under the specified license (see [the tests section from our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#tests))
- [ ] I have properly formatted metadata files (see [our formatting guide](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#format-metadata-files))
- [ ] I have added thorough tests (see [the tests section from our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))
- [ ] I have filled all places where my pull request accesses files, network, docker, or any other external service (see the section above)

2023-09-08 12:15 UTC, msupic requested changes

2023-09-08 12:15 UTC, msupic commented on tests/src/log4j/log4j/1.2.17/src/test/resources/log4j.xml
> +<!DOCTYPE log4j:configuration PUBLIC "-//log4j/log4j Configuration//EN" "log4j.dtd">
Is this file copied from some web page?

2023-09-08 13:24 UTC, FoghostCn commented on tests/src/log4j/log4j/1.2.17/src/test/resources/log4j.xml
> +<!DOCTYPE log4j:configuration PUBLIC "-//log4j/log4j Configuration//EN" "log4j.dtd">
sorry for that, I'll fix it

2023-09-08 14:03 UTC, msupic requested changes

2023-09-08 14:03 UTC, msupic commented on tests/src/log4j/log4j/1.2.17/src/test/java/log4j/log4j/Log4jTest.java
> +    void consoleInfoLogger() {
A few more things: The `consoleInfoLogger` and `consoleInfoLoggerProperties` tests create the `logs` folder and the following files in it:
```
dailyRollingAppender.log
fileAppender.log
rollingFileAppender.log
```
Can you check at the end of each test that the expected message exist in those files, something like:
```
    String loggedMessage = Files.readAllLines(Paths.get(filePath)).get(0);
    assertThat(loggedMessage).contains("info message ");
```
and delete the `logs` folder after each executed test. The `deletion` code can be added to the following method
```
    @AfterEach
    public void tearDown() {
        System.setOut(systemOut);
    }
```

2023-09-11 05:48 UTC, msupic commented
@FoghostCn - tests are failing. It looks like that some metadata are missing:
```
JUnit Jupiter:Log4jTest:consoleInfoLoggerProperties()
    MethodSource [className = 'log4j.log4j.Log4jTest', methodName = 'consoleInfoLoggerProperties', methodParameterTypes = '']
    => java.lang.NoClassDefFoundError: Could not initialize class org.apache.log4j.LogManager
       org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:415)
       log4j.log4j.Log4jTest.consoleInfoLoggerProperties(Log4jTest.java:52)
```

2023-09-11 10:52 UTC, FoghostCn commented
I have regenerate a reflect-config.json file,it should be right

2023-09-11 11:32 UTC, msupic commented
@FoghostCn - Tests are still failing. You can reproduce the issue locally by executing
`./gradlew test -Pcoordinates=log4j:log4j:1.2.17`

2023-09-11 11:49 UTC, FoghostCn commented
Thank you so much,I've run successed locally

2023-09-11 12:15 UTC, msupic commented
Resource metadata for `log4j.xml` and `log4j.dtd` already exists here: [metadata/log4j/log4j/1.2.17/resource-config.json](https://github.com/FoghostCn/graalvm-reachability-metadata/blob/master/metadata/log4j/log4j/1.2.17/resource-config.json), so you can just add the following entry to the same file instead of creating new resource-config.json file that is used only in tests
```
      {
        "condition": {
          "typeReachable": "org.apache.log4j.helpers.Loader"
        },
        "pattern": "\\Qlog4j.properties\\E"
      }
```

2023-09-11 12:49 UTC, FoghostCn commented
OK,I will fix it tomorrow,I'm not next to the computer right now.

2023-09-12 04:58 UTC, FoghostCn commented
> Resource metadata for `log4j.xml` and `log4j.dtd` already exists here: [metadata/log4j/log4j/1.2.17/resource-config.json](https://github.com/FoghostCn/graalvm-reachability-metadata/blob/master/metadata/log4j/log4j/1.2.17/resource-config.json), so you can just add the following entry to the same file instead of creating new resource-config.json file that is used only in tests
> 
> ```
>       {
>         "condition": {
>           "typeReachable": "org.apache.log4j.helpers.Loader"
>         },
>         "pattern": "\\Qlog4j.properties\\E"
>       }
> ```

done

2023-09-12 05:33 UTC, msupic approved these changes

2023-09-12 05:33 UTC, merged